### ISSUE TITLE
TypeError: Expected str, not <class 'pydantic.v1.types.SecretStr'>

### ISSUE THREAD

**Issue by jianshi88** [ScrapeGraphAI/Scrapegraph-ai#445]
--- Executing Fetch Node ---
--- (Fetching HTML from: https://www.wired.com/category/science/) ---
--- Executing Parse Node ---
--- Executing RAG Node ---
--- (updated chunks metadata) ---
ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7b37a7bc4670>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_plugin_wrapping.py", line 105, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/transport/grpc.py", line 95, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_plugin_wrapping.py", line 74, in __call__
    self._callback(metadata, cygrpc.StatusCode.ok, None)
  File "src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi", line 52, in grpc._cython.cygrpc._get_metadata.callback
  File "src/python/grpcio/grpc/_cython/_cygrpc/metadata.pyx.pxi", line 43, in grpc._cython.cygrpc._store_c_metadata
  File "src/python/grpcio/grpc/_cython/_cygrpc/grpc_string.pyx.pxi", line 40, in grpc._cython.cygrpc._encode
TypeError: Expected str, not <class 'pydantic.v1.types.SecretStr'>

I encountered this issue while running the smartgraph in Colab. I am using the Gemini model and have not made any changes to the code. Can you help me check what the problem is

**Comment by VinciGit00** [comment]
pls try now with the new version

**Comment by lucasseidor33** [comment]
i have the same errore with langchain-google-genai  GoogleGenerativeAIEmbeddings  method, how is a  way to resolve this? pls help
