### ISSUE TITLE
Missing load dotenv on openai example

### ISSUE THREAD

**Issue by DragonelRoland** [ScrapeGraphAI/Scrapegraph-ai#473]
**Describe the bug**
Discovered a bug on smart_scraper_opanai example where it's missing the dotenv import.

**To Reproduce**
Run smart_scraper_opanai.py

**Expected behavior**
The scrip should load the openai api key.

**Desktop (please complete the following information):**
Macbook

Fix: 
line 8 in smart_scraper_opanai.py, add:
from dotenv import load_dotenv
load_dotenv()

Error:
➜  ScrapeGraphAI /usr/local/bin/python3 /Users/rolandgraser/Documents/Dokumente/Busin
ess/Agents/ScrapeGraphAI/examples/openai/smart_scraper_openai.py
Traceback (most recent call last):
  File "/Users/rolandgraser/Library/Python/3.12/lib/python/site-packages/scrapegraphai/graphs/abstract_graph.py", line 156, in _create_llm
    self.model_token = models_tokens["openai"][llm_params["model"]]
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'gpt-4o-mini'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rolandgraser/Documents/Dokumente/Business/Agents/ScrapeGraphAI/examples/openai/smart_scraper_openai.py", line 28, in <module>
    smart_scraper_graph = SmartScraperGraph(
                          ^^^^^^^^^^^^^^^^^^
  File "/Users/rolandgraser/Library/Python/3.12/lib/python/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 53, in __init__
    super().__init__(prompt, config, source, schema)
  File "/Users/rolandgraser/Library/Python/3.12/lib/python/site-packages/scrapegraphai/graphs/abstract_graph.py", line 76, in __init__
    self.llm_model = self._create_llm(config["llm"], chat=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rolandgraser/Library/Python/3.12/lib/python/site-packages/scrapegraphai/graphs/abstract_graph.py", line 158, in _create_llm
    raise KeyError("Model not supported") from exc
KeyError: 'Model not supported'
➜  ScrapeGraphAI

**Comment by VinciGit00** [comment]
hi. please install the new beta
