### ISSUE TITLE
NameError: name 'input_data' is not defined

### ISSUE THREAD

**Issue by AliRezaPython1375** [ScrapeGraphAI/Scrapegraph-ai#527]
this is my sample example:

import json
from scrapegraphai.graphs import SmartScraperGraph
from statics import OPENAI_API_KEY

# Define the configuration for the scraping pipeline
graph_config = {
    "llm": {
        "api_key": OPENAI_API_KEY,
        "model": "gpt-4o-mini",
    },
    "verbose": True,
    "headless": False,
}

# Create the SmartScraperGraph instance
smart_scraper_graph = SmartScraperGraph(
    prompt="Find some information about what does the company do, the name and a contact email.",
    source="https://scrapegraphai.com/",
    config=graph_config
)

# Run the pipeline
result = smart_scraper_graph.run()
print(json.dumps(result, indent=4))

and this is my error:

plementation that is significantly slower. If possible, please configure a c build environment and compile the extension
  warnings.warn(_SLOW_CRC32C_WARNING, RuntimeWarning)
--- Executing Fetch Node ---
--- (Fetching HTML from: https://scrapegraphai.com/) ---
Traceback (most recent call last):
  File "e:\Learn\11\main.py", line 23, in <module>
    result = smart_scraper_graph.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.shahmohammadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapegraphai\graphs\smart_scraper_graph.py", line 114, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.shahmohammadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 265, in execute
    return self._execute_standard(initial_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.shahmohammadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 187, in _execute_standard
    raise e
  File "C:\Users\a.shahmohammadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 171, in _execute_standard
    result = current_node.execute(state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.shahmohammadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapegraphai\nodes\fetch_node.py", line 132, in execute
    return self.handle_web_source(state, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a.shahmohammadi\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapegraphai\nodes\fetch_node.py", line 291, in handle_web_source 
    parsed_content = convert_to_md(document[0].page_content, input_data[0])
                                                             ^^^^^^^^^^
NameError: name 'input_data' is not defined

and this is my version:

scrapegraphai                            1.13.1

please help!

**Comment by VinciGit00** [comment]
hi please update to the new version
