### ISSUE TITLE
`embedder_model` AttributeError in `/examples/openai/deep_scraper_openai.py`

### ISSUE THREAD

**Issue by ajt** [ScrapeGraphAI/Scrapegraph-ai#545]
**Describe the bug**
When running the OpenAI Deep Scraper example located at `examples/openai/deep_scraper_openai.py`, I get the error:
```
Traceback (most recent call last):
  File "/Users/ajt/Projects/scrapegraph_playground/openai/deep_scraper_openai.py", line 37, in <module>
    deep_scraper_graph = DeepScraperGraph(
                         ^^^^^^^^^^^^^^^^^
  File "/Users/ajt/.virtualenvs/scrapegraph-ai/lib/python3.12/site-packages/scrapegraphai/graphs/deep_scraper_graph.py", line 62, in __init__
    super().__init__(prompt, config, source, schema)
  File "/Users/ajt/.virtualenvs/scrapegraph-ai/lib/python3.12/site-packages/scrapegraphai/graphs/abstract_graph.py", line 70, in __init__
    self.graph = self._create_graph()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajt/.virtualenvs/scrapegraph-ai/lib/python3.12/site-packages/scrapegraphai/graphs/deep_scraper_graph.py", line 160, in _create_graph
    base_graph = self._create_repeated_graph()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajt/.virtualenvs/scrapegraph-ai/lib/python3.12/site-packages/scrapegraphai/graphs/deep_scraper_graph.py", line 90, in _create_repeated_graph
    "embedder_model": self.embedder_model
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeepScraperGraph' object has no attribute 'embedder_model'
```

**To Reproduce**
Fresh install on macOS.
Execute the script

**Expected behavior**
Expecting the script to execute without errors.

**Desktop (please complete the following information):**
 - OS: MacOS 13.6.7
 - Browser chrome

**Additional context**
I am sure that the `embedder_model` just needs to be set, but I am unsure how to do it.

**Comment by ekinsenler** [comment]
You can refer to #544 . `DeepScraperGraph` is currently not working as intended.

**Comment by f-aguzzi** [comment]
The `DeepScraperGraph` was never finished. There is a new graph with similar features called `DepthSearchGraph` added in version 1.26
