### ISSUE TITLE
TypeError: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'str'>

### ISSUE THREAD

**Issue by JINO-ROHIT** [ScrapeGraphAI/Scrapegraph-ai#588]
I get this error when trying to run the example code from groq smart scrapper.

```
""" 
Basic example of scraping pipeline using SmartScraper
"""

import os
from dotenv import load_dotenv
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

load_dotenv()

# ************************************************
# Define the configuration for the graph
# ************************************************

#groq_key = os.getenv("GROQ_APIKEY")

graph_config = {
    "llm": {
        "model_instance": "groq/gemma-7b-it",
        "model_tokens" : 5000,
        "api_key": groq_key,
        "temperature": 0
    },
    "headless": False
}

# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the projects with their description.",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects/",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))
```

**Comment by VinciGit00** [comment]
Can you write the whole output?

**Comment by JINO-ROHIT** [comment]
@VinciGit00  yeap

```
Traceback (most recent call last):
  File "E:\scraper\groq_smartscraper.py", line 40, in <module>
    result = smart_scraper_graph.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scraper\.env\Lib\site-packages\scrapegraphai\graphs\smart_scraper_graph.py", line 114, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scraper\.env\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 263, in execute
    return self._execute_standard(initial_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scraper\.env\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 185, in _execute_standard
    raise e
  File "E:\scraper\.env\Lib\site-packages\scrapegraphai\graphs\base_graph.py", line 169, in _execute_standard
    result = current_node.execute(state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scraper\.env\Lib\site-packages\scrapegraphai\nodes\generate_answer_node.py", line 128, in execute
    chain =  prompt | self.llm_model | output_parser
             ~~~~~~~^~~~~~~~~~~~~~~~
  File "E:\scraper\.env\Lib\site-packages\langchain_core\runnables\base.py", line 436, in __or__
    return RunnableSequence(self, coerce_to_runnable(other))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\scraper\.env\Lib\site-packages\langchain_core\runnables\base.py", line 5552, in coerce_to_runnable
    raise TypeError(
TypeError: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'str'>
```

**Comment by VinciGit00** [comment]
Look at #587

**Comment by JINO-ROHIT** [comment]
@VinciGit00 hey it still doesnt work, this is a completely different issue

**Comment by SumeraMartin** [comment]
I have the similar issue but I got <class 'NoneType'> at the end

```
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/llm/llm_scraper.py", line 86, in _scrape_with_scrapegraph
    result = smart_scraper_graph.run()
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 114, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 263, in execute
    return self._execute_standard(initial_state)
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 185, in _execute_standard
    raise e
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 169, in _execute_standard
    result = current_node.execute(state)
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/scrapegraphai/nodes/generate_answer_node.py", line 133, in execute
    chain =  prompt | self.llm_model | output_parser
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 436, in __or__
    return RunnableSequence(self, coerce_to_runnable(other))
  File "/Users/martinsumera/projects/ai/lekarna-listing-ai/backend/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 5552, in coerce_to_runnable
    raise TypeError(
TypeError: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'NoneType'>
```

**Comment by SumeraMartin** [comment]
But update to scrapegraphai==1.15.0b8 fixed it 👍

**Comment by SumeraMartin** [comment]
I think that you don't have to. As I mentioned in the second comment. It already works with scrapegraphai==1.15.0b8

**Comment by anth0nyhak1m** [comment]
I upgraded to scrapegraphai==1.16.0 and am still getting this error when trying to use bedrock.
