### ISSUE TITLE
v1.15.1: burr dependency not optional

### ISSUE THREAD

**Issue by LorenzoPaleari** [ScrapeGraphAI/Scrapegraph-ai#610]
**Describe the bug**
Burr package is required in order to start any example of ScrapeGraphAI.

**To Reproduce**
```bash
pip install scrapegraphai
playwright install
python3 smart_scraper_openai.py # examples/openai/smart_scraper_openai.py
```

**Expected behaviour**
Burr should be installed only if used. 

```bash
(venv) lollo@Lorenzos-MacBook-Pro test % python3 smart_scraper_openai.py 
Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/burr_bridge.py", line 13, in <module>
    import burr
ModuleNotFoundError: No module named 'burr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/smart_scraper_openai.py", line 8, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/__init__.py", line 6, in <module>
    from .base_graph import BaseGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/base_graph.py", line 8, in <module>
    from ..integrations import BurrBridge
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/__init__.py", line 5, in <module>
    from .burr_bridge import BurrBridge
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/integrations/burr_bridge.py", line 18, in <module>
    raise ImportError("burr package is not installed. Please install it with 'pip install scrapegraphai[burr]'")
ImportError: burr package is not installed. Please install it with 'pip install scrapegraphai[burr]'
```

**Desktop (please complete the following information):**
 - OS: MacOsX - MacBookPro 2018
 - Version: python3.11

**Comment by VinciGit00** [comment]
which version are you using?

**Comment by LorenzoPaleari** [comment]
1.15.1

**Comment by VinciGit00** [comment]
hi please update to the new version.
I will close the issue.
Let me know if you still have problems

**Comment by ocdnamib** [comment]
Hello, I am experiencing the same error on version 1.50.0

**Comment by VinciGit00** [comment]
@ocdnamib does it work with version 1.58?

**Comment by ocdnamib** [comment]
did you mean 1.48.0 ? cannot find 1.58.0

**Comment by ocdnamib** [comment]
I figured out that when installing burr with scrapwithgraph it installed burr 0.22, I tried with latest 0.39 but error remained.

**Comment by VinciGit00** [comment]
@ocdnamib do you need burr?

**Comment by ocdnamib** [comment]
i don't "need" I was just testing according to documentation. 
is it out of scope/roadmap now ?
