### ISSUE TITLE
v1.17.0b5: No module named 'PIL'

### ISSUE THREAD

**Issue by LorenzoPaleari** [ScrapeGraphAI/Scrapegraph-ai#627]
**Describe the bug**
When using 1.17 beta 5 there is an import error from screenshot scraping.
`ModuleNotFoundError: No module named 'PIL'`

**To Reproduce**
```bash
python3.11 -m venv venv
source venv/bin/activate
pip install scrapegraphai==1.17.0b5

python3 smart_scraper_openai.py # Any example actually
```

**Log**
```bash
(venv) lollo@Lorenzos-MacBook-Pro test % python3 smart_scraper_openai.py       
Traceback (most recent call last):
  File "/Users/lollo/Desktop/test/smart_scraper_openai.py", line 8, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/__init__.py", line 5, in <module>
    from .abstract_graph import AbstractGraph
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 16, in <module>
    from ..utils.logging import set_verbosity_warning, set_verbosity_info
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/utils/__init__.py", line 14, in <module>
    from .screenshot_scraping.screenshot_preparation import take_screenshot, select_area_with_opencv, select_area_with_ipywidget, crop_image
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/utils/screenshot_scraping/__init__.py", line 1, in <module>
    from .screenshot_preparation import take_screenshot, select_area_with_opencv, select_area_with_ipywidget, crop_image
  File "/Users/lollo/Desktop/test/venv/lib/python3.11/site-packages/scrapegraphai/utils/screenshot_scraping/screenshot_preparation.py", line 6, in <module>
    from PIL import Image, ImageGrab
ModuleNotFoundError: No module named 'PIL'
```

**Desktop (please complete the following information):**
 - OS: MacOsX - MacBookPro 2018
 - Version: 1.17.0-beta5

**Comment by LorenzoPaleari** [comment]
Tested, I do not have anymore the error.
But I guess I shouldn't be able to close issues myself?
