### ISSUE TITLE
Bedrock model copy recursion

### ISSUE THREAD

**Issue by rjbks** [ScrapeGraphAI/Scrapegraph-ai#669]
**Describe the bug**
Using scrapegraph with bedrock client causes recursion limit exceeded seemingly due to attempting to copy the boto3 client

**To Reproduce**
```python
client = boto3.client("bedrock-runtime", region_name="us-west-2")
sg = SearchGraph(
                    prompt=prompt,
                    config={
                        "llm": {
                            "client": client,
                            "model": "bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
                            "temperature": 0.0
                        },
                        "verbose": False,
                        "max_results": 4,
                        "headless": True,
                    },
                    schema=MatchedSchool
                )
                result = sg.run()
```

**Desktop (please complete the following information):**
 - OS:macos
 - Browser chrome
 - Version [e.g. 22]: 1.19

**Additional context**
File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/scrapegraphai/utils/copy.py", line 30, in safe_deepcopy
    return copy.deepcopy(obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.lock' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 908, in __getattr__
    service_id = self._service_model.service_id.hyphenize()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 935, in _service_model
    return self.meta.service_model
           ^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 908, in __getattr__
    service_id = self._service_model.service_id.hyphenize()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 935, in _service_model
    return self.meta.service_model
           ^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 908, in __getattr__
    service_id = self._service_model.service_id.hyphenize()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 935, in _service_model
    return self.meta.service_model
           ^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 908, in __getattr__
    service_id = self._service_model.service_id.hyphenize()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 935, in _service_model
    return self.meta.service_model
           ^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 908, in __getattr__
    service_id = self._service_model.service_id.hyphenize()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/med_device/lib/python3.12/site-packages/botocore/client.py", line 935, in _service_model
    return self.meta.service_model
...
recursion limit exceeded

**Comment by goasleep** [comment]
This was a situation that had not been considered before. I will be compatible with this situation. Thanks your feedback~

**Comment by VinciGit00** [comment]
hi please update to the new main version
