### ISSUE TITLE
Import Error. 

### ISSUE THREAD

**Issue by anth0nyhak1m** [ScrapeGraphAI/Scrapegraph-ai#695]
I have scrapegraphai v 1.21.0

Could not import 'from scrapegraphai.graphs import SmartScraperGraph'

Got this scary thing:

C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\langchain\chat_models\__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import init_chat_model`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AnthonyHakim\lynx\foci-ml\human_resources\scrape_private_board.py", line 1, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\scrapegraphai\graphs\__init__.py", line 5, in <module>
    from .abstract_graph import AbstractGraph
  File "C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\scrapegraphai\graphs\abstract_graph.py", line 9, in <module>
    from langchain.chat_models import init_chat_model
ImportError: cannot import name 'init_chat_model' from 'langchain.chat_models' (C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\langchain\chat_models\__init__.py)

I ran pip install -U langchain-community

Now I am getting this issue:
Traceback (most recent call last):
  File "C:\Users\AnthonyHakim\lynx\foci-ml\test_scrapeai.py", line 1, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\scrapegraphai\graphs\__init__.py", line 5, in <module>
    from .abstract_graph import AbstractGraph
  File "C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\scrapegraphai\graphs\abstract_graph.py", line 12, in <module>
    from ..models import (
  File "C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\scrapegraphai\models\__init__.py", line 5, in <module>
    from .openai_tts import OpenAITextToSpeech
  File "C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\scrapegraphai\models\openai_tts.py", line 5, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (C:\Users\AnthonyHakim\anaconda3\envs\test-env\Lib\site-packages\openai\__init__.py)

**Comment by VinciGit00** [comment]
Please provide me the code

**Comment by anth0nyhak1m** [comment]
I had an environment issue
