### ISSUE TITLE
SearchGraph Invalid json output

### ISSUE THREAD

**Issue by Gege-Wang** [ScrapeGraphAI/Scrapegraph-ai#733]
**Describe the bug**
when I use searchGraph, I meet the following error.
```bash
Traceback (most recent call last):
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/output_parsers/json.py", line 83, in parse_result
    return parse_json_markdown(text)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/utils/json.py", line 144, in parse_json_markdown
    return _parse_json(json_str, parser=parser)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/utils/json.py", line 160, in _parse_json
    return parser(json_str)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/utils/json.py", line 118, in parse_partial_json
    return json.loads(s, strict=strict)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 16 column 5 (char 504)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/miyamo/pdfscrawl.py", line 90, in <module>
    result = search_graph.run()
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/search_graph.py", line 120, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 259, in execute
    return self._execute_standard(initial_state)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 180, in _execute_standard
    raise e
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 164, in _execute_standard
    result = current_node.execute(state)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/nodes/graph_iterator_node.py", line 73, in execute
    state = asyncio.run(self._async_execute(state, batchsize))
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/nodes/graph_iterator_node.py", line 136, in _async_execute
    answers = await tqdm.gather(
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/nodes/graph_iterator_node.py", line 126, in _async_run
    return await asyncio.to_thread(graph.run)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 115, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 259, in execute
    return self._execute_standard(initial_state)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 180, in _execute_standard
    raise e
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 164, in _execute_standard
    result = current_node.execute(state)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/scrapegraphai/nodes/generate_answer_node.py", line 111, in execute
    batch_results = async_runner.invoke({"question": user_prompt})
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3723, in invoke
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3723, in <dictcomp>
    output = {key: future.result() for key, future in zip(steps, futures)}
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3707, in _invoke_step
    return context.run(
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3022, in invoke
    input = context.run(step.invoke, input, config)
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 192, in invoke
    return self._call_with_config(
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1926, in _call_with_config
    context.run(
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 394, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 193, in <lambda>
    lambda inner_input: self.parse_result(
  File "/Users/miyamo/miniconda3/envs/mofa/lib/python3.10/site-packages/langchain_core/output_parsers/json.py", line 86, in parse_result
    raise OutputParserException(msg, llm_output=text) from e
langchain_core.exceptions.OutputParserException: Invalid json output: ```json
{
  "answer": null,
  "question": {
    "title": "Finding the first positive number in the array",
    "url": "/questions/74095793/finding-the-first-positive-number-in-the-array"
  },
  "relatedQuestions": [
    {
      "title": "Question score (upvotes - downvotes)",
      "url": "/questions/74095793/finding-the-first-positive-number-in-the-array"
    },
    {
      "title": "Question score (upvotes - downvotes)",
      "url": "/questions/21225399/first-non-negative-element-in-an-array"
    },
    // ... Other related questions...
  ]
}
```

**To Reproduce**
source code 
```python
"""
Example of Search Graph
"""
import os
from dotenv import load_dotenv
from scrapegraphai.graphs import SearchGraph
from scrapegraphai.utils import convert_to_csv, convert_to_json, prettify_exec_info

# ************************************************
# Define the configuration for the graph
# ************************************************

load_dotenv()

groq_key = os.getenv("GROQ_APIKEY")

graph_config = {
    "llm": {
        "model": "groq/gemma-7b-it",
        "api_key": "",
        "temperature": 0
    },
    "headless": False
}

# ************************************************
# Create the SearchGraph instance and run it
# ************************************************

search_graph = SearchGraph(
    prompt="give me the first positive number",
    config=graph_config
)

result = search_graph.run()
print(result)
```

**Desktop :**
 - OS: MacOS

**Comment by VinciGit00** [comment]
pls try with openAI

**Comment by VinciGit00** [comment]
the main problem is gemma, I tried to add new info to the prompts, please update to the new beta

**Comment by VinciGit00** [comment]
please update to the new version
