### ISSUE TITLE
using SmartScraperGraph for PDF file --- AttributeError: 'FetchNode' object has no attribute 'update_state'

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [ScrapeGraphAI/Scrapegraph-ai#759]
**scrapegraphai version : 1.26.7**

Source Code Reference : https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/groq/smart_scraper_groq.py

Code:
```
""" 
Basic example of scraping pipeline using SmartScraper
"""

import os
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info


groq_key = 'abc'

graph_config = {
    "llm": {
        "model": "groq/gemma-7b-it",
        "api_key": groq_key,
        "temperature": 0
    },
    "headless": False,
}


# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************


input_pdf_file = 'input/ex1.pdf'

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the product no, order no, number of units of all certified products.",
    source=input_pdf_file,
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))

```
ERROR:

```
python3 main.py 
Traceback (most recent call last):
  File "/home/arslan/Data/Learning/side_projects/scrapegraph_ai/main.py", line 35, in <module>
    result = smart_scraper_graph.run()
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 184, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 279, in execute
    return self._execute_standard(initial_state)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 195, in _execute_standard
    raise e
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 179, in _execute_standard
    result = current_node.execute(state)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/nodes/fetch_node.py", line 128, in execute
    return self.handle_local_source(state, source)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/nodes/fetch_node.py", line 233, in handle_local_source
    return self.update_state(state, compressed_document)
AttributeError: 'FetchNode' object has no attribute 'update_state'

```

**Comment by VinciGit00** [comment]
you should have looked on this example instead [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/openai/md_scraper_openai.py](url)

**Comment by Arslan-Mehmood1** [comment]
@VinciGit00 the document is not clear on what graphs to use for scraping what kind of files.
It would be great if a table is provided with mapping for each scraper graph. Thanks
