### ISSUE TITLE
langchain_core.exceptions.OutputParserException: Invalid json output: ```json

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [ScrapeGraphAI/Scrapegraph-ai#760]
scrapegraphai version : 1.26.7

Source Code Reference : https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/groq/smart_scraper_groq.py

Code:
```
""" 
Basic example of scraping pipeline using SmartScraper
"""

import os
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info


groq_key = 'abc'

graph_config = {
    "llm": {
        "model": "groq/gemma-7b-it",
        "api_key": groq_key,
        "temperature": 0
    },
    "headless": False,
}


# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

# list me all the products on all the pages
urls = ['https://sandbox.oxylabs.io/products']

smart_scraper_graph = SmartScraperGraph(
    prompt="list me all the products on all the pages",
    source=urls[0],
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))
```
ERROR:

```
python3 main.py 
Traceback (most recent call last):
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/output_parsers/json.py", line 83, in parse_result
    return parse_json_markdown(text)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/utils/json.py", line 144, in parse_json_markdown
    return _parse_json(json_str, parser=parser)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/utils/json.py", line 160, in _parse_json
    return parser(json_str)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/utils/json.py", line 118, in parse_partial_json
    return json.loads(s, strict=strict)
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 15 column 5 (char 263)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arslan/Data/Learning/side_projects/scrapegraph_ai/main.py", line 39, in <module>
    result = smart_scraper_graph.run()
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 184, in run
    self.final_state, self.execution_info = self.graph.execute(inputs)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 279, in execute
    return self._execute_standard(initial_state)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 195, in _execute_standard
    raise e
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/graphs/base_graph.py", line 179, in _execute_standard
    result = current_node.execute(state)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/scrapegraphai/nodes/generate_answer_node.py", line 126, in execute
    answer =  chain.invoke({"question": user_prompt})
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3024, in invoke
    input = context.run(step.invoke, input, config)
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 193, in invoke
    return self._call_with_config(
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1927, in _call_with_config
    context.run(
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 396, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 194, in <lambda>
    lambda inner_input: self.parse_result(
  File "/home/arslan/.virtualenvs/scrapegraph_ai/lib/python3.10/site-packages/langchain_core/output_parsers/json.py", line 86, in parse_result
    raise OutputParserException(msg, llm_output=text) from e
langchain_core.exceptions.OutputParserException: Invalid json output: ```json
{
  "products": [
    {
      "name": "The Legend of Zelda: Ocarina of Time",
      "price": "91,99 €"
    },
    {
      "name": "Super Mario Galaxy",
      "price": "89,99 €"
    },
    {
      "name": "Super Mario Odyssey",
      "price": "89,99 €"
    },
    // ... Remaining products and their prices
  ]
}

For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE
```

**Comment by VinciGit00** [comment]
hi the main reason is because of this   "model": "groq/gemma-7b-it".
The problem is that Gemma does not always give a json and it crack the code

**Comment by Arslan-Mehmood1** [comment]
> hi the main reason is because of this "model": "groq/gemma-7b-it". The problem is that Gemma does not always give a json and it crack the code

You are right. Thanks
